export const ReasonCodes = {
  LOW_REVENUE: 'LOW_REVENUE',
  HIGH_LOAN_RATIO: 'HIGH_LOAN_RATIO',
  LOW_REPAYMENT_CAPACITY: 'LOW_REPAYMENT_CAPACITY',
  EXTREME_TENURE: 'EXTREME_TENURE',
  DATA_INCONSISTENCY: 'DATA_INCONSISTENCY',
  INVALID_PAN_FORMAT: 'INVALID_PAN_FORMAT',
  APPROVED: 'APPROVED',
};